[build]
target = ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]
rustflags = ["-C", "link-self-contained=yes", "-C", "linker=rust-lld"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
